---
title: "RNA-seq Power"
output: pdf_document
classoption: portrait
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(PROPER)
library(kableExtra)
powerDf <- readRDS(file = "powerDf.Rds")
powerDf$`Actual FDR` <- round(powerDf$`Actual FDR`, digits = 4)
powerDf$`Marginal Power` <- round(powerDf$`Marginal Power`, digits = 4)
```

```{r}
knitr::kable(powerDf[,-6], booktabs = TRUE, longtable = TRUE, linesep = "") %>% 
  kable_styling(full_width = FALSE, position = "center", font_size = 10, latex_options = c("striped", "hold_position", "repeat_header"), stripe_index = c(c(c(1, 2, 3, 4, 5) + 5),
                                                                                                                                     c(c(1, 2, 3, 4, 5) + 5*3),
                                                                                                                                     c(c(1, 2, 3, 4, 5) + 5*5),
                                                                                                                                     c(c(1, 2, 3, 4, 5) + 5*7),
                                                                                                                                     c(c(1, 2, 3, 4, 5) + 5*9),
                                                                                                                                     c(c(1, 2, 3, 4, 5) + 5*11),
                                                                                                                                     c(c(1, 2, 3, 4, 5) + 5*13),
                                                                                                                                     c(c(1, 2, 3, 4, 5) + 5*15),
                                                                                                                                     c(c(1, 2, 3, 4, 5) + 5*17),
                                                                                                                                     c(c(1, 2, 3, 4, 5) + 5*19),
                                                                                                                                     c(c(1, 2, 3, 4, 5) + 5*21),
                                                                                                                                     c(c(1, 2, 3, 4, 5) + 5*23)))
```